//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema_alertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class area_contratos
    {
        public area_contratos()
        {
            this.contratos = new HashSet<contrato>();
            this.Borradorcontratos = new HashSet<Borradorcontrato>();
        }
    
        public int Area_ContratoId { get; set; }
        public string Nombre_Area { get; set; }
    
        public virtual ICollection<contrato> contratos { get; set; }
        public virtual ICollection<Borradorcontrato> Borradorcontratos { get; set; }
    }
}
