//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema_alertas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class sistema_alertasEntities : DbContext
    {
        public sistema_alertasEntities()
            : base("name=sistema_alertasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<area_contratos> area_contratos { get; set; }
        public DbSet<Borradorcontrato> Borradorcontratos { get; set; }
        public DbSet<contrato> contratos { get; set; }
        public DbSet<estado> estados { get; set; }
        public DbSet<metodo_pagos> metodo_pagos { get; set; }
        public DbSet<orden_compras> orden_compras { get; set; }
        public DbSet<perfile> perfiles { get; set; }
        public DbSet<permiso> permisos { get; set; }
        public DbSet<producto> productos { get; set; }
        public DbSet<proveedore> proveedores { get; set; }
        public DbSet<recordatorio> recordatorios { get; set; }
        public DbSet<tarjeta> tarjetas { get; set; }
        public DbSet<tipo_contratos> tipo_contratos { get; set; }
        public DbSet<tipo_pagos> tipo_pagos { get; set; }
        public DbSet<tipo_proveedores> tipo_proveedores { get; set; }
        public DbSet<tipo_tarjetas> tipo_tarjetas { get; set; }
        public DbSet<unidad_negocios> unidad_negocios { get; set; }
        public DbSet<usuario> usuarios { get; set; }
        public DbSet<usuarios_perfiles_permisos> usuarios_perfiles_permisos { get; set; }
    
        public virtual ObjectResult<AboutToFinishContractByAreaForReportPDF_Result> AboutToFinishContractByAreaForReportPDF(Nullable<int> codigoArea)
        {
            var codigoAreaParameter = codigoArea.HasValue ?
                new ObjectParameter("CodigoArea", codigoArea) :
                new ObjectParameter("CodigoArea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AboutToFinishContractByAreaForReportPDF_Result>("AboutToFinishContractByAreaForReportPDF", codigoAreaParameter);
        }
    
        public virtual ObjectResult<AboutToFinishContractForReportPDF_Result> AboutToFinishContractForReportPDF()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AboutToFinishContractForReportPDF_Result>("AboutToFinishContractForReportPDF");
        }
    
        public virtual ObjectResult<ActiveContractByAreaForReportPDF_Result> ActiveContractByAreaForReportPDF(Nullable<int> codigoArea)
        {
            var codigoAreaParameter = codigoArea.HasValue ?
                new ObjectParameter("CodigoArea", codigoArea) :
                new ObjectParameter("CodigoArea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActiveContractByAreaForReportPDF_Result>("ActiveContractByAreaForReportPDF", codigoAreaParameter);
        }
    
        public virtual ObjectResult<ActiveContractForReportPDF_Result> ActiveContractForReportPDF()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActiveContractForReportPDF_Result>("ActiveContractForReportPDF");
        }
    
        public virtual ObjectResult<AllDetailsContractByAreaForReportPDF_Result> AllDetailsContractByAreaForReportPDF(Nullable<int> codigoArea)
        {
            var codigoAreaParameter = codigoArea.HasValue ?
                new ObjectParameter("CodigoArea", codigoArea) :
                new ObjectParameter("CodigoArea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllDetailsContractByAreaForReportPDF_Result>("AllDetailsContractByAreaForReportPDF", codigoAreaParameter);
        }
    
        public virtual ObjectResult<AllDetailsContractForReportPDF_Result> AllDetailsContractForReportPDF()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllDetailsContractForReportPDF_Result>("AllDetailsContractForReportPDF");
        }
    
        public virtual ObjectResult<defeatedContractByAreaForReportPDF_Result> defeatedContractByAreaForReportPDF(Nullable<int> codigoArea)
        {
            var codigoAreaParameter = codigoArea.HasValue ?
                new ObjectParameter("CodigoArea", codigoArea) :
                new ObjectParameter("CodigoArea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<defeatedContractByAreaForReportPDF_Result>("defeatedContractByAreaForReportPDF", codigoAreaParameter);
        }
    
        public virtual ObjectResult<defeatedContractForReportPDF_Result> defeatedContractForReportPDF()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<defeatedContractForReportPDF_Result>("defeatedContractForReportPDF");
        }
    
        public virtual int SP_DeleteAreaContratos(Nullable<int> areaContratosId)
        {
            var areaContratosIdParameter = areaContratosId.HasValue ?
                new ObjectParameter("AreaContratosId", areaContratosId) :
                new ObjectParameter("AreaContratosId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteAreaContratos", areaContratosIdParameter);
        }
    
        public virtual int SP_DeleteContract(Nullable<int> contratoId)
        {
            var contratoIdParameter = contratoId.HasValue ?
                new ObjectParameter("ContratoId", contratoId) :
                new ObjectParameter("ContratoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteContract", contratoIdParameter);
        }
    
        public virtual int SP_DeleteDraftContract(Nullable<int> contratoId)
        {
            var contratoIdParameter = contratoId.HasValue ?
                new ObjectParameter("ContratoId", contratoId) :
                new ObjectParameter("ContratoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteDraftContract", contratoIdParameter);
        }
    
        public virtual int SP_DeleteMethodPaymentById(Nullable<int> metodoPagoId)
        {
            var metodoPagoIdParameter = metodoPagoId.HasValue ?
                new ObjectParameter("MetodoPagoId", metodoPagoId) :
                new ObjectParameter("MetodoPagoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteMethodPaymentById", metodoPagoIdParameter);
        }
    
        public virtual int SP_DeleteOrdenCompras(Nullable<int> ordenCompraId)
        {
            var ordenCompraIdParameter = ordenCompraId.HasValue ?
                new ObjectParameter("OrdenCompraId", ordenCompraId) :
                new ObjectParameter("OrdenCompraId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteOrdenCompras", ordenCompraIdParameter);
        }
    
        public virtual int SP_DeleteProduct(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteProduct", productIdParameter);
        }
    
        public virtual int SP_DeleteProvider(Nullable<int> proveedorId)
        {
            var proveedorIdParameter = proveedorId.HasValue ?
                new ObjectParameter("ProveedorId", proveedorId) :
                new ObjectParameter("ProveedorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteProvider", proveedorIdParameter);
        }
    
        public virtual int SP_DeleteTarjetas(Nullable<int> tarjetaId)
        {
            var tarjetaIdParameter = tarjetaId.HasValue ?
                new ObjectParameter("TarjetaId", tarjetaId) :
                new ObjectParameter("TarjetaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteTarjetas", tarjetaIdParameter);
        }
    
        public virtual int SP_DeleteTipoContratos(Nullable<int> tipoContratosId)
        {
            var tipoContratosIdParameter = tipoContratosId.HasValue ?
                new ObjectParameter("TipoContratosId", tipoContratosId) :
                new ObjectParameter("TipoContratosId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteTipoContratos", tipoContratosIdParameter);
        }
    
        public virtual int SP_DeleteUnidadNegocios(Nullable<int> unidadNegocioId)
        {
            var unidadNegocioIdParameter = unidadNegocioId.HasValue ?
                new ObjectParameter("UnidadNegocioId", unidadNegocioId) :
                new ObjectParameter("UnidadNegocioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteUnidadNegocios", unidadNegocioIdParameter);
        }
    
        public virtual int SP_DeleteUser(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteUser", usuarioIdParameter);
        }
    
        public virtual int SP_EditAreaContratos(Nullable<int> areaContratosId, string nombre_Area)
        {
            var areaContratosIdParameter = areaContratosId.HasValue ?
                new ObjectParameter("AreaContratosId", areaContratosId) :
                new ObjectParameter("AreaContratosId", typeof(int));
    
            var nombre_AreaParameter = nombre_Area != null ?
                new ObjectParameter("Nombre_Area", nombre_Area) :
                new ObjectParameter("Nombre_Area", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EditAreaContratos", areaContratosIdParameter, nombre_AreaParameter);
        }
    
        public virtual int SP_EditContratos(Nullable<int> contratoId, string nombre_Contrato, string numero_Contrato, string numero_Servicio_Contrato, string gastos, Nullable<System.DateTime> fecha_Inicio, Nullable<System.DateTime> fecha_Finalizacion, Nullable<decimal> costo_Total, Nullable<decimal> costo_Por_Cada_Pago, Nullable<System.DateTime> fecha_Renovacion_Pago, Nullable<int> cantidad_Licencias, string garantia, Nullable<System.DateTime> fecha_Vencimiento_Garantia, Nullable<System.DateTime> fecha_Creacion, string descripcion, string direccion_Archivo, Nullable<int> proveedor_ManufactureroId, Nullable<int> proveedor_Distribuidor, Nullable<int> usuario_AprobadorId, Nullable<int> usuario_AdministradorId, Nullable<int> tipo_ContratoId, Nullable<int> metodo_PagoId, Nullable<int> unidad_NegocioId, Nullable<int> tipo_PagoId, Nullable<int> orden_CompraId, Nullable<int> tarjetaId, Nullable<int> area_ContratoId, Nullable<int> productoId, Nullable<int> recordatorioId, Nullable<int> estadoId, string detalles_Producto)
        {
            var contratoIdParameter = contratoId.HasValue ?
                new ObjectParameter("ContratoId", contratoId) :
                new ObjectParameter("ContratoId", typeof(int));
    
            var nombre_ContratoParameter = nombre_Contrato != null ?
                new ObjectParameter("Nombre_Contrato", nombre_Contrato) :
                new ObjectParameter("Nombre_Contrato", typeof(string));
    
            var numero_ContratoParameter = numero_Contrato != null ?
                new ObjectParameter("Numero_Contrato", numero_Contrato) :
                new ObjectParameter("Numero_Contrato", typeof(string));
    
            var numero_Servicio_ContratoParameter = numero_Servicio_Contrato != null ?
                new ObjectParameter("Numero_Servicio_Contrato", numero_Servicio_Contrato) :
                new ObjectParameter("Numero_Servicio_Contrato", typeof(string));
    
            var gastosParameter = gastos != null ?
                new ObjectParameter("Gastos", gastos) :
                new ObjectParameter("Gastos", typeof(string));
    
            var fecha_InicioParameter = fecha_Inicio.HasValue ?
                new ObjectParameter("Fecha_Inicio", fecha_Inicio) :
                new ObjectParameter("Fecha_Inicio", typeof(System.DateTime));
    
            var fecha_FinalizacionParameter = fecha_Finalizacion.HasValue ?
                new ObjectParameter("Fecha_Finalizacion", fecha_Finalizacion) :
                new ObjectParameter("Fecha_Finalizacion", typeof(System.DateTime));
    
            var costo_TotalParameter = costo_Total.HasValue ?
                new ObjectParameter("Costo_Total", costo_Total) :
                new ObjectParameter("Costo_Total", typeof(decimal));
    
            var costo_Por_Cada_PagoParameter = costo_Por_Cada_Pago.HasValue ?
                new ObjectParameter("Costo_Por_Cada_Pago", costo_Por_Cada_Pago) :
                new ObjectParameter("Costo_Por_Cada_Pago", typeof(decimal));
    
            var fecha_Renovacion_PagoParameter = fecha_Renovacion_Pago.HasValue ?
                new ObjectParameter("Fecha_Renovacion_Pago", fecha_Renovacion_Pago) :
                new ObjectParameter("Fecha_Renovacion_Pago", typeof(System.DateTime));
    
            var cantidad_LicenciasParameter = cantidad_Licencias.HasValue ?
                new ObjectParameter("Cantidad_Licencias", cantidad_Licencias) :
                new ObjectParameter("Cantidad_Licencias", typeof(int));
    
            var garantiaParameter = garantia != null ?
                new ObjectParameter("Garantia", garantia) :
                new ObjectParameter("Garantia", typeof(string));
    
            var fecha_Vencimiento_GarantiaParameter = fecha_Vencimiento_Garantia.HasValue ?
                new ObjectParameter("Fecha_Vencimiento_Garantia", fecha_Vencimiento_Garantia) :
                new ObjectParameter("Fecha_Vencimiento_Garantia", typeof(System.DateTime));
    
            var fecha_CreacionParameter = fecha_Creacion.HasValue ?
                new ObjectParameter("Fecha_Creacion", fecha_Creacion) :
                new ObjectParameter("Fecha_Creacion", typeof(System.DateTime));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var direccion_ArchivoParameter = direccion_Archivo != null ?
                new ObjectParameter("Direccion_Archivo", direccion_Archivo) :
                new ObjectParameter("Direccion_Archivo", typeof(string));
    
            var proveedor_ManufactureroIdParameter = proveedor_ManufactureroId.HasValue ?
                new ObjectParameter("Proveedor_ManufactureroId", proveedor_ManufactureroId) :
                new ObjectParameter("Proveedor_ManufactureroId", typeof(int));
    
            var proveedor_DistribuidorParameter = proveedor_Distribuidor.HasValue ?
                new ObjectParameter("Proveedor_Distribuidor", proveedor_Distribuidor) :
                new ObjectParameter("Proveedor_Distribuidor", typeof(int));
    
            var usuario_AprobadorIdParameter = usuario_AprobadorId.HasValue ?
                new ObjectParameter("Usuario_AprobadorId", usuario_AprobadorId) :
                new ObjectParameter("Usuario_AprobadorId", typeof(int));
    
            var usuario_AdministradorIdParameter = usuario_AdministradorId.HasValue ?
                new ObjectParameter("Usuario_AdministradorId", usuario_AdministradorId) :
                new ObjectParameter("Usuario_AdministradorId", typeof(int));
    
            var tipo_ContratoIdParameter = tipo_ContratoId.HasValue ?
                new ObjectParameter("Tipo_ContratoId", tipo_ContratoId) :
                new ObjectParameter("Tipo_ContratoId", typeof(int));
    
            var metodo_PagoIdParameter = metodo_PagoId.HasValue ?
                new ObjectParameter("Metodo_PagoId", metodo_PagoId) :
                new ObjectParameter("Metodo_PagoId", typeof(int));
    
            var unidad_NegocioIdParameter = unidad_NegocioId.HasValue ?
                new ObjectParameter("Unidad_NegocioId", unidad_NegocioId) :
                new ObjectParameter("Unidad_NegocioId", typeof(int));
    
            var tipo_PagoIdParameter = tipo_PagoId.HasValue ?
                new ObjectParameter("Tipo_PagoId", tipo_PagoId) :
                new ObjectParameter("Tipo_PagoId", typeof(int));
    
            var orden_CompraIdParameter = orden_CompraId.HasValue ?
                new ObjectParameter("Orden_CompraId", orden_CompraId) :
                new ObjectParameter("Orden_CompraId", typeof(int));
    
            var tarjetaIdParameter = tarjetaId.HasValue ?
                new ObjectParameter("TarjetaId", tarjetaId) :
                new ObjectParameter("TarjetaId", typeof(int));
    
            var area_ContratoIdParameter = area_ContratoId.HasValue ?
                new ObjectParameter("Area_ContratoId", area_ContratoId) :
                new ObjectParameter("Area_ContratoId", typeof(int));
    
            var productoIdParameter = productoId.HasValue ?
                new ObjectParameter("ProductoId", productoId) :
                new ObjectParameter("ProductoId", typeof(int));
    
            var recordatorioIdParameter = recordatorioId.HasValue ?
                new ObjectParameter("RecordatorioId", recordatorioId) :
                new ObjectParameter("RecordatorioId", typeof(int));
    
            var estadoIdParameter = estadoId.HasValue ?
                new ObjectParameter("EstadoId", estadoId) :
                new ObjectParameter("EstadoId", typeof(int));
    
            var detalles_ProductoParameter = detalles_Producto != null ?
                new ObjectParameter("Detalles_Producto", detalles_Producto) :
                new ObjectParameter("Detalles_Producto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EditContratos", contratoIdParameter, nombre_ContratoParameter, numero_ContratoParameter, numero_Servicio_ContratoParameter, gastosParameter, fecha_InicioParameter, fecha_FinalizacionParameter, costo_TotalParameter, costo_Por_Cada_PagoParameter, fecha_Renovacion_PagoParameter, cantidad_LicenciasParameter, garantiaParameter, fecha_Vencimiento_GarantiaParameter, fecha_CreacionParameter, descripcionParameter, direccion_ArchivoParameter, proveedor_ManufactureroIdParameter, proveedor_DistribuidorParameter, usuario_AprobadorIdParameter, usuario_AdministradorIdParameter, tipo_ContratoIdParameter, metodo_PagoIdParameter, unidad_NegocioIdParameter, tipo_PagoIdParameter, orden_CompraIdParameter, tarjetaIdParameter, area_ContratoIdParameter, productoIdParameter, recordatorioIdParameter, estadoIdParameter, detalles_ProductoParameter);
        }
    
        public virtual int SP_EditMethodPaymentById(Nullable<int> metodoPagoId, string nombre_Metodo_Pago)
        {
            var metodoPagoIdParameter = metodoPagoId.HasValue ?
                new ObjectParameter("MetodoPagoId", metodoPagoId) :
                new ObjectParameter("MetodoPagoId", typeof(int));
    
            var nombre_Metodo_PagoParameter = nombre_Metodo_Pago != null ?
                new ObjectParameter("Nombre_Metodo_Pago", nombre_Metodo_Pago) :
                new ObjectParameter("Nombre_Metodo_Pago", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EditMethodPaymentById", metodoPagoIdParameter, nombre_Metodo_PagoParameter);
        }
    
        public virtual int SP_EditOrdenCompras(Nullable<int> ordenCompraId, Nullable<System.DateTime> fecha_Ultima_Orden_Compra, string ultimo_Numero_Factura, string codigo_Presupuestario_2016, string monto_Previo, string direccion_Archivo)
        {
            var ordenCompraIdParameter = ordenCompraId.HasValue ?
                new ObjectParameter("OrdenCompraId", ordenCompraId) :
                new ObjectParameter("OrdenCompraId", typeof(int));
    
            var fecha_Ultima_Orden_CompraParameter = fecha_Ultima_Orden_Compra.HasValue ?
                new ObjectParameter("Fecha_Ultima_Orden_Compra", fecha_Ultima_Orden_Compra) :
                new ObjectParameter("Fecha_Ultima_Orden_Compra", typeof(System.DateTime));
    
            var ultimo_Numero_FacturaParameter = ultimo_Numero_Factura != null ?
                new ObjectParameter("Ultimo_Numero_Factura", ultimo_Numero_Factura) :
                new ObjectParameter("Ultimo_Numero_Factura", typeof(string));
    
            var codigo_Presupuestario_2016Parameter = codigo_Presupuestario_2016 != null ?
                new ObjectParameter("Codigo_Presupuestario_2016", codigo_Presupuestario_2016) :
                new ObjectParameter("Codigo_Presupuestario_2016", typeof(string));
    
            var monto_PrevioParameter = monto_Previo != null ?
                new ObjectParameter("Monto_Previo", monto_Previo) :
                new ObjectParameter("Monto_Previo", typeof(string));
    
            var direccion_ArchivoParameter = direccion_Archivo != null ?
                new ObjectParameter("Direccion_Archivo", direccion_Archivo) :
                new ObjectParameter("Direccion_Archivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EditOrdenCompras", ordenCompraIdParameter, fecha_Ultima_Orden_CompraParameter, ultimo_Numero_FacturaParameter, codigo_Presupuestario_2016Parameter, monto_PrevioParameter, direccion_ArchivoParameter);
        }
    
        public virtual int SP_EditProduct(Nullable<int> productoId, string nombre_Producto, Nullable<decimal> precio, string descripcion, string direccion_Fotografia, Nullable<int> proveedor_ManufactureroId, Nullable<int> proveedor_DistribuidorId)
        {
            var productoIdParameter = productoId.HasValue ?
                new ObjectParameter("ProductoId", productoId) :
                new ObjectParameter("ProductoId", typeof(int));
    
            var nombre_ProductoParameter = nombre_Producto != null ?
                new ObjectParameter("Nombre_Producto", nombre_Producto) :
                new ObjectParameter("Nombre_Producto", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var direccion_FotografiaParameter = direccion_Fotografia != null ?
                new ObjectParameter("Direccion_Fotografia", direccion_Fotografia) :
                new ObjectParameter("Direccion_Fotografia", typeof(string));
    
            var proveedor_ManufactureroIdParameter = proveedor_ManufactureroId.HasValue ?
                new ObjectParameter("Proveedor_ManufactureroId", proveedor_ManufactureroId) :
                new ObjectParameter("Proveedor_ManufactureroId", typeof(int));
    
            var proveedor_DistribuidorIdParameter = proveedor_DistribuidorId.HasValue ?
                new ObjectParameter("Proveedor_DistribuidorId", proveedor_DistribuidorId) :
                new ObjectParameter("Proveedor_DistribuidorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EditProduct", productoIdParameter, nombre_ProductoParameter, precioParameter, descripcionParameter, direccion_FotografiaParameter, proveedor_ManufactureroIdParameter, proveedor_DistribuidorIdParameter);
        }
    
        public virtual int SP_EditProvider(Nullable<int> proveedorId, string nombre_Proveedor, string correo_Proveedor, string nombre_Contacto, string telefono_Contacto, string ubicacion, string descripcion, Nullable<int> tipo_ProveedorId)
        {
            var proveedorIdParameter = proveedorId.HasValue ?
                new ObjectParameter("ProveedorId", proveedorId) :
                new ObjectParameter("ProveedorId", typeof(int));
    
            var nombre_ProveedorParameter = nombre_Proveedor != null ?
                new ObjectParameter("Nombre_Proveedor", nombre_Proveedor) :
                new ObjectParameter("Nombre_Proveedor", typeof(string));
    
            var correo_ProveedorParameter = correo_Proveedor != null ?
                new ObjectParameter("Correo_Proveedor", correo_Proveedor) :
                new ObjectParameter("Correo_Proveedor", typeof(string));
    
            var nombre_ContactoParameter = nombre_Contacto != null ?
                new ObjectParameter("Nombre_Contacto", nombre_Contacto) :
                new ObjectParameter("Nombre_Contacto", typeof(string));
    
            var telefono_ContactoParameter = telefono_Contacto != null ?
                new ObjectParameter("Telefono_Contacto", telefono_Contacto) :
                new ObjectParameter("Telefono_Contacto", typeof(string));
    
            var ubicacionParameter = ubicacion != null ?
                new ObjectParameter("Ubicacion", ubicacion) :
                new ObjectParameter("Ubicacion", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var tipo_ProveedorIdParameter = tipo_ProveedorId.HasValue ?
                new ObjectParameter("Tipo_ProveedorId", tipo_ProveedorId) :
                new ObjectParameter("Tipo_ProveedorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EditProvider", proveedorIdParameter, nombre_ProveedorParameter, correo_ProveedorParameter, nombre_ContactoParameter, telefono_ContactoParameter, ubicacionParameter, descripcionParameter, tipo_ProveedorIdParameter);
        }
    
        public virtual int SP_EditTarjetas(Nullable<int> tarjetaId, string ultimos_Digitos_Tarjeta, Nullable<System.DateTime> fecha_Vencimiento_Tarjeta, string nombre_Persona_Asignada_A_Yarjeta, Nullable<int> tipo_TarjetaId)
        {
            var tarjetaIdParameter = tarjetaId.HasValue ?
                new ObjectParameter("TarjetaId", tarjetaId) :
                new ObjectParameter("TarjetaId", typeof(int));
    
            var ultimos_Digitos_TarjetaParameter = ultimos_Digitos_Tarjeta != null ?
                new ObjectParameter("Ultimos_Digitos_Tarjeta", ultimos_Digitos_Tarjeta) :
                new ObjectParameter("Ultimos_Digitos_Tarjeta", typeof(string));
    
            var fecha_Vencimiento_TarjetaParameter = fecha_Vencimiento_Tarjeta.HasValue ?
                new ObjectParameter("Fecha_Vencimiento_Tarjeta", fecha_Vencimiento_Tarjeta) :
                new ObjectParameter("Fecha_Vencimiento_Tarjeta", typeof(System.DateTime));
    
            var nombre_Persona_Asignada_A_YarjetaParameter = nombre_Persona_Asignada_A_Yarjeta != null ?
                new ObjectParameter("Nombre_Persona_Asignada_A_Yarjeta", nombre_Persona_Asignada_A_Yarjeta) :
                new ObjectParameter("Nombre_Persona_Asignada_A_Yarjeta", typeof(string));
    
            var tipo_TarjetaIdParameter = tipo_TarjetaId.HasValue ?
                new ObjectParameter("Tipo_TarjetaId", tipo_TarjetaId) :
                new ObjectParameter("Tipo_TarjetaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EditTarjetas", tarjetaIdParameter, ultimos_Digitos_TarjetaParameter, fecha_Vencimiento_TarjetaParameter, nombre_Persona_Asignada_A_YarjetaParameter, tipo_TarjetaIdParameter);
        }
    
        public virtual int SP_EditTipoContratos(Nullable<int> tipoContratosId, string nombre_Tipo_Contrato, string descripcion)
        {
            var tipoContratosIdParameter = tipoContratosId.HasValue ?
                new ObjectParameter("TipoContratosId", tipoContratosId) :
                new ObjectParameter("TipoContratosId", typeof(int));
    
            var nombre_Tipo_ContratoParameter = nombre_Tipo_Contrato != null ?
                new ObjectParameter("Nombre_Tipo_Contrato", nombre_Tipo_Contrato) :
                new ObjectParameter("Nombre_Tipo_Contrato", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EditTipoContratos", tipoContratosIdParameter, nombre_Tipo_ContratoParameter, descripcionParameter);
        }
    
        public virtual int SP_EditUnidadNegociosById(Nullable<int> unidadNegocioId, string numero_Unidad_Negocio, string nombre_Unidad_Negocio, string nombre_Previo_Unidad_Negocio)
        {
            var unidadNegocioIdParameter = unidadNegocioId.HasValue ?
                new ObjectParameter("UnidadNegocioId", unidadNegocioId) :
                new ObjectParameter("UnidadNegocioId", typeof(int));
    
            var numero_Unidad_NegocioParameter = numero_Unidad_Negocio != null ?
                new ObjectParameter("Numero_Unidad_Negocio", numero_Unidad_Negocio) :
                new ObjectParameter("Numero_Unidad_Negocio", typeof(string));
    
            var nombre_Unidad_NegocioParameter = nombre_Unidad_Negocio != null ?
                new ObjectParameter("Nombre_Unidad_Negocio", nombre_Unidad_Negocio) :
                new ObjectParameter("Nombre_Unidad_Negocio", typeof(string));
    
            var nombre_Previo_Unidad_NegocioParameter = nombre_Previo_Unidad_Negocio != null ?
                new ObjectParameter("Nombre_Previo_Unidad_Negocio", nombre_Previo_Unidad_Negocio) :
                new ObjectParameter("Nombre_Previo_Unidad_Negocio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EditUnidadNegociosById", unidadNegocioIdParameter, numero_Unidad_NegocioParameter, nombre_Unidad_NegocioParameter, nombre_Previo_Unidad_NegocioParameter);
        }
    
        public virtual int SP_EditUser(Nullable<int> usuarioId, string nombre, string apellido, string email, string pass, string telefono, string codigo_Usuario, string username, string direccion_Fotografia, Nullable<int> perfilId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var codigo_UsuarioParameter = codigo_Usuario != null ?
                new ObjectParameter("Codigo_Usuario", codigo_Usuario) :
                new ObjectParameter("Codigo_Usuario", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var direccion_FotografiaParameter = direccion_Fotografia != null ?
                new ObjectParameter("Direccion_Fotografia", direccion_Fotografia) :
                new ObjectParameter("Direccion_Fotografia", typeof(string));
    
            var perfilIdParameter = perfilId.HasValue ?
                new ObjectParameter("PerfilId", perfilId) :
                new ObjectParameter("PerfilId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EditUser", usuarioIdParameter, nombreParameter, apellidoParameter, emailParameter, passParameter, telefonoParameter, codigo_UsuarioParameter, usernameParameter, direccion_FotografiaParameter, perfilIdParameter);
        }
    
        public virtual int SP_insertarAreaContratos(string nombre_Area)
        {
            var nombre_AreaParameter = nombre_Area != null ?
                new ObjectParameter("Nombre_Area", nombre_Area) :
                new ObjectParameter("Nombre_Area", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insertarAreaContratos", nombre_AreaParameter);
        }
    
        public virtual int SP_insertarBorradorContratos(string nombre_Contrato, string numero_Contrato, string numero_Servicio_Contrato, string gastos2, Nullable<System.DateTime> fecha_Inicio, Nullable<System.DateTime> fecha_Finalizacion, Nullable<decimal> costo_Total, Nullable<decimal> costo_Por_Cada_Pago, Nullable<System.DateTime> fecha_Renovacion_Pago, Nullable<int> cantidad_Licencias, string garantia, Nullable<System.DateTime> fecha_Vencimiento_Garantia, Nullable<System.DateTime> fecha_Creacion, string descripcion, string direccion_Archivo, Nullable<int> proveedor_ManufactureroId, Nullable<int> proveedor_Distribuidor, Nullable<int> usuario_AprobadorId, Nullable<int> usuario_AdministradorId, Nullable<int> tipo_ContratoId, Nullable<int> metodo_PagoId, Nullable<int> unidad_NegocioId, Nullable<int> tipo_PagoId, Nullable<int> orden_CompraId, Nullable<int> tarjetaId, Nullable<int> area_ContratoId, Nullable<int> productoId, Nullable<int> recordatorioId, Nullable<int> estadoId, string detalles_Producto)
        {
            var nombre_ContratoParameter = nombre_Contrato != null ?
                new ObjectParameter("Nombre_Contrato", nombre_Contrato) :
                new ObjectParameter("Nombre_Contrato", typeof(string));
    
            var numero_ContratoParameter = numero_Contrato != null ?
                new ObjectParameter("Numero_Contrato", numero_Contrato) :
                new ObjectParameter("Numero_Contrato", typeof(string));
    
            var numero_Servicio_ContratoParameter = numero_Servicio_Contrato != null ?
                new ObjectParameter("Numero_Servicio_Contrato", numero_Servicio_Contrato) :
                new ObjectParameter("Numero_Servicio_Contrato", typeof(string));
    
            var gastos2Parameter = gastos2 != null ?
                new ObjectParameter("Gastos2", gastos2) :
                new ObjectParameter("Gastos2", typeof(string));
    
            var fecha_InicioParameter = fecha_Inicio.HasValue ?
                new ObjectParameter("Fecha_Inicio", fecha_Inicio) :
                new ObjectParameter("Fecha_Inicio", typeof(System.DateTime));
    
            var fecha_FinalizacionParameter = fecha_Finalizacion.HasValue ?
                new ObjectParameter("Fecha_Finalizacion", fecha_Finalizacion) :
                new ObjectParameter("Fecha_Finalizacion", typeof(System.DateTime));
    
            var costo_TotalParameter = costo_Total.HasValue ?
                new ObjectParameter("Costo_Total", costo_Total) :
                new ObjectParameter("Costo_Total", typeof(decimal));
    
            var costo_Por_Cada_PagoParameter = costo_Por_Cada_Pago.HasValue ?
                new ObjectParameter("Costo_Por_Cada_Pago", costo_Por_Cada_Pago) :
                new ObjectParameter("Costo_Por_Cada_Pago", typeof(decimal));
    
            var fecha_Renovacion_PagoParameter = fecha_Renovacion_Pago.HasValue ?
                new ObjectParameter("Fecha_Renovacion_Pago", fecha_Renovacion_Pago) :
                new ObjectParameter("Fecha_Renovacion_Pago", typeof(System.DateTime));
    
            var cantidad_LicenciasParameter = cantidad_Licencias.HasValue ?
                new ObjectParameter("Cantidad_Licencias", cantidad_Licencias) :
                new ObjectParameter("Cantidad_Licencias", typeof(int));
    
            var garantiaParameter = garantia != null ?
                new ObjectParameter("Garantia", garantia) :
                new ObjectParameter("Garantia", typeof(string));
    
            var fecha_Vencimiento_GarantiaParameter = fecha_Vencimiento_Garantia.HasValue ?
                new ObjectParameter("Fecha_Vencimiento_Garantia", fecha_Vencimiento_Garantia) :
                new ObjectParameter("Fecha_Vencimiento_Garantia", typeof(System.DateTime));
    
            var fecha_CreacionParameter = fecha_Creacion.HasValue ?
                new ObjectParameter("Fecha_Creacion", fecha_Creacion) :
                new ObjectParameter("Fecha_Creacion", typeof(System.DateTime));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var direccion_ArchivoParameter = direccion_Archivo != null ?
                new ObjectParameter("Direccion_Archivo", direccion_Archivo) :
                new ObjectParameter("Direccion_Archivo", typeof(string));
    
            var proveedor_ManufactureroIdParameter = proveedor_ManufactureroId.HasValue ?
                new ObjectParameter("Proveedor_ManufactureroId", proveedor_ManufactureroId) :
                new ObjectParameter("Proveedor_ManufactureroId", typeof(int));
    
            var proveedor_DistribuidorParameter = proveedor_Distribuidor.HasValue ?
                new ObjectParameter("Proveedor_Distribuidor", proveedor_Distribuidor) :
                new ObjectParameter("Proveedor_Distribuidor", typeof(int));
    
            var usuario_AprobadorIdParameter = usuario_AprobadorId.HasValue ?
                new ObjectParameter("Usuario_AprobadorId", usuario_AprobadorId) :
                new ObjectParameter("Usuario_AprobadorId", typeof(int));
    
            var usuario_AdministradorIdParameter = usuario_AdministradorId.HasValue ?
                new ObjectParameter("Usuario_AdministradorId", usuario_AdministradorId) :
                new ObjectParameter("Usuario_AdministradorId", typeof(int));
    
            var tipo_ContratoIdParameter = tipo_ContratoId.HasValue ?
                new ObjectParameter("Tipo_ContratoId", tipo_ContratoId) :
                new ObjectParameter("Tipo_ContratoId", typeof(int));
    
            var metodo_PagoIdParameter = metodo_PagoId.HasValue ?
                new ObjectParameter("Metodo_PagoId", metodo_PagoId) :
                new ObjectParameter("Metodo_PagoId", typeof(int));
    
            var unidad_NegocioIdParameter = unidad_NegocioId.HasValue ?
                new ObjectParameter("Unidad_NegocioId", unidad_NegocioId) :
                new ObjectParameter("Unidad_NegocioId", typeof(int));
    
            var tipo_PagoIdParameter = tipo_PagoId.HasValue ?
                new ObjectParameter("Tipo_PagoId", tipo_PagoId) :
                new ObjectParameter("Tipo_PagoId", typeof(int));
    
            var orden_CompraIdParameter = orden_CompraId.HasValue ?
                new ObjectParameter("Orden_CompraId", orden_CompraId) :
                new ObjectParameter("Orden_CompraId", typeof(int));
    
            var tarjetaIdParameter = tarjetaId.HasValue ?
                new ObjectParameter("TarjetaId", tarjetaId) :
                new ObjectParameter("TarjetaId", typeof(int));
    
            var area_ContratoIdParameter = area_ContratoId.HasValue ?
                new ObjectParameter("Area_ContratoId", area_ContratoId) :
                new ObjectParameter("Area_ContratoId", typeof(int));
    
            var productoIdParameter = productoId.HasValue ?
                new ObjectParameter("ProductoId", productoId) :
                new ObjectParameter("ProductoId", typeof(int));
    
            var recordatorioIdParameter = recordatorioId.HasValue ?
                new ObjectParameter("RecordatorioId", recordatorioId) :
                new ObjectParameter("RecordatorioId", typeof(int));
    
            var estadoIdParameter = estadoId.HasValue ?
                new ObjectParameter("EstadoId", estadoId) :
                new ObjectParameter("EstadoId", typeof(int));
    
            var detalles_ProductoParameter = detalles_Producto != null ?
                new ObjectParameter("Detalles_Producto", detalles_Producto) :
                new ObjectParameter("Detalles_Producto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insertarBorradorContratos", nombre_ContratoParameter, numero_ContratoParameter, numero_Servicio_ContratoParameter, gastos2Parameter, fecha_InicioParameter, fecha_FinalizacionParameter, costo_TotalParameter, costo_Por_Cada_PagoParameter, fecha_Renovacion_PagoParameter, cantidad_LicenciasParameter, garantiaParameter, fecha_Vencimiento_GarantiaParameter, fecha_CreacionParameter, descripcionParameter, direccion_ArchivoParameter, proveedor_ManufactureroIdParameter, proveedor_DistribuidorParameter, usuario_AprobadorIdParameter, usuario_AdministradorIdParameter, tipo_ContratoIdParameter, metodo_PagoIdParameter, unidad_NegocioIdParameter, tipo_PagoIdParameter, orden_CompraIdParameter, tarjetaIdParameter, area_ContratoIdParameter, productoIdParameter, recordatorioIdParameter, estadoIdParameter, detalles_ProductoParameter);
        }
    
        public virtual int SP_insertarContratos(string nombre_Contrato, string numero_Contrato, string numero_Servicio_Contrato, string gastos, Nullable<System.DateTime> fecha_Inicio, Nullable<System.DateTime> fecha_Finalizacion, Nullable<decimal> costo_Total, Nullable<decimal> costo_Por_Cada_Pago, Nullable<System.DateTime> fecha_Renovacion_Pago, Nullable<int> cantidad_Licencias, string garantia, Nullable<System.DateTime> fecha_Vencimiento_Garantia, Nullable<System.DateTime> fecha_Creacion, string descripcion, string direccion_Archivo, Nullable<int> proveedor_ManufactureroId, Nullable<int> proveedor_Distribuidor, Nullable<int> usuario_AprobadorId, Nullable<int> usuario_AdministradorId, Nullable<int> tipo_ContratoId, Nullable<int> metodo_PagoId, Nullable<int> unidad_NegocioId, Nullable<int> tipo_PagoId, Nullable<int> orden_CompraId, Nullable<int> tarjetaId, Nullable<int> area_ContratoId, Nullable<int> productoId, Nullable<int> recordatorioId, Nullable<int> estadoId, string detalles_Producto)
        {
            var nombre_ContratoParameter = nombre_Contrato != null ?
                new ObjectParameter("Nombre_Contrato", nombre_Contrato) :
                new ObjectParameter("Nombre_Contrato", typeof(string));
    
            var numero_ContratoParameter = numero_Contrato != null ?
                new ObjectParameter("Numero_Contrato", numero_Contrato) :
                new ObjectParameter("Numero_Contrato", typeof(string));
    
            var numero_Servicio_ContratoParameter = numero_Servicio_Contrato != null ?
                new ObjectParameter("Numero_Servicio_Contrato", numero_Servicio_Contrato) :
                new ObjectParameter("Numero_Servicio_Contrato", typeof(string));
    
            var gastosParameter = gastos != null ?
                new ObjectParameter("Gastos", gastos) :
                new ObjectParameter("Gastos", typeof(string));
    
            var fecha_InicioParameter = fecha_Inicio.HasValue ?
                new ObjectParameter("Fecha_Inicio", fecha_Inicio) :
                new ObjectParameter("Fecha_Inicio", typeof(System.DateTime));
    
            var fecha_FinalizacionParameter = fecha_Finalizacion.HasValue ?
                new ObjectParameter("Fecha_Finalizacion", fecha_Finalizacion) :
                new ObjectParameter("Fecha_Finalizacion", typeof(System.DateTime));
    
            var costo_TotalParameter = costo_Total.HasValue ?
                new ObjectParameter("Costo_Total", costo_Total) :
                new ObjectParameter("Costo_Total", typeof(decimal));
    
            var costo_Por_Cada_PagoParameter = costo_Por_Cada_Pago.HasValue ?
                new ObjectParameter("Costo_Por_Cada_Pago", costo_Por_Cada_Pago) :
                new ObjectParameter("Costo_Por_Cada_Pago", typeof(decimal));
    
            var fecha_Renovacion_PagoParameter = fecha_Renovacion_Pago.HasValue ?
                new ObjectParameter("Fecha_Renovacion_Pago", fecha_Renovacion_Pago) :
                new ObjectParameter("Fecha_Renovacion_Pago", typeof(System.DateTime));
    
            var cantidad_LicenciasParameter = cantidad_Licencias.HasValue ?
                new ObjectParameter("Cantidad_Licencias", cantidad_Licencias) :
                new ObjectParameter("Cantidad_Licencias", typeof(int));
    
            var garantiaParameter = garantia != null ?
                new ObjectParameter("Garantia", garantia) :
                new ObjectParameter("Garantia", typeof(string));
    
            var fecha_Vencimiento_GarantiaParameter = fecha_Vencimiento_Garantia.HasValue ?
                new ObjectParameter("Fecha_Vencimiento_Garantia", fecha_Vencimiento_Garantia) :
                new ObjectParameter("Fecha_Vencimiento_Garantia", typeof(System.DateTime));
    
            var fecha_CreacionParameter = fecha_Creacion.HasValue ?
                new ObjectParameter("Fecha_Creacion", fecha_Creacion) :
                new ObjectParameter("Fecha_Creacion", typeof(System.DateTime));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var direccion_ArchivoParameter = direccion_Archivo != null ?
                new ObjectParameter("Direccion_Archivo", direccion_Archivo) :
                new ObjectParameter("Direccion_Archivo", typeof(string));
    
            var proveedor_ManufactureroIdParameter = proveedor_ManufactureroId.HasValue ?
                new ObjectParameter("Proveedor_ManufactureroId", proveedor_ManufactureroId) :
                new ObjectParameter("Proveedor_ManufactureroId", typeof(int));
    
            var proveedor_DistribuidorParameter = proveedor_Distribuidor.HasValue ?
                new ObjectParameter("Proveedor_Distribuidor", proveedor_Distribuidor) :
                new ObjectParameter("Proveedor_Distribuidor", typeof(int));
    
            var usuario_AprobadorIdParameter = usuario_AprobadorId.HasValue ?
                new ObjectParameter("Usuario_AprobadorId", usuario_AprobadorId) :
                new ObjectParameter("Usuario_AprobadorId", typeof(int));
    
            var usuario_AdministradorIdParameter = usuario_AdministradorId.HasValue ?
                new ObjectParameter("Usuario_AdministradorId", usuario_AdministradorId) :
                new ObjectParameter("Usuario_AdministradorId", typeof(int));
    
            var tipo_ContratoIdParameter = tipo_ContratoId.HasValue ?
                new ObjectParameter("Tipo_ContratoId", tipo_ContratoId) :
                new ObjectParameter("Tipo_ContratoId", typeof(int));
    
            var metodo_PagoIdParameter = metodo_PagoId.HasValue ?
                new ObjectParameter("Metodo_PagoId", metodo_PagoId) :
                new ObjectParameter("Metodo_PagoId", typeof(int));
    
            var unidad_NegocioIdParameter = unidad_NegocioId.HasValue ?
                new ObjectParameter("Unidad_NegocioId", unidad_NegocioId) :
                new ObjectParameter("Unidad_NegocioId", typeof(int));
    
            var tipo_PagoIdParameter = tipo_PagoId.HasValue ?
                new ObjectParameter("Tipo_PagoId", tipo_PagoId) :
                new ObjectParameter("Tipo_PagoId", typeof(int));
    
            var orden_CompraIdParameter = orden_CompraId.HasValue ?
                new ObjectParameter("Orden_CompraId", orden_CompraId) :
                new ObjectParameter("Orden_CompraId", typeof(int));
    
            var tarjetaIdParameter = tarjetaId.HasValue ?
                new ObjectParameter("TarjetaId", tarjetaId) :
                new ObjectParameter("TarjetaId", typeof(int));
    
            var area_ContratoIdParameter = area_ContratoId.HasValue ?
                new ObjectParameter("Area_ContratoId", area_ContratoId) :
                new ObjectParameter("Area_ContratoId", typeof(int));
    
            var productoIdParameter = productoId.HasValue ?
                new ObjectParameter("ProductoId", productoId) :
                new ObjectParameter("ProductoId", typeof(int));
    
            var recordatorioIdParameter = recordatorioId.HasValue ?
                new ObjectParameter("RecordatorioId", recordatorioId) :
                new ObjectParameter("RecordatorioId", typeof(int));
    
            var estadoIdParameter = estadoId.HasValue ?
                new ObjectParameter("EstadoId", estadoId) :
                new ObjectParameter("EstadoId", typeof(int));
    
            var detalles_ProductoParameter = detalles_Producto != null ?
                new ObjectParameter("Detalles_Producto", detalles_Producto) :
                new ObjectParameter("Detalles_Producto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insertarContratos", nombre_ContratoParameter, numero_ContratoParameter, numero_Servicio_ContratoParameter, gastosParameter, fecha_InicioParameter, fecha_FinalizacionParameter, costo_TotalParameter, costo_Por_Cada_PagoParameter, fecha_Renovacion_PagoParameter, cantidad_LicenciasParameter, garantiaParameter, fecha_Vencimiento_GarantiaParameter, fecha_CreacionParameter, descripcionParameter, direccion_ArchivoParameter, proveedor_ManufactureroIdParameter, proveedor_DistribuidorParameter, usuario_AprobadorIdParameter, usuario_AdministradorIdParameter, tipo_ContratoIdParameter, metodo_PagoIdParameter, unidad_NegocioIdParameter, tipo_PagoIdParameter, orden_CompraIdParameter, tarjetaIdParameter, area_ContratoIdParameter, productoIdParameter, recordatorioIdParameter, estadoIdParameter, detalles_ProductoParameter);
        }
    
        public virtual int SP_insertarEstados(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insertarEstados", descripcionParameter);
        }
    
        public virtual int SP_insertarMetodoPagos(string nombre_Metodo_Pago)
        {
            var nombre_Metodo_PagoParameter = nombre_Metodo_Pago != null ?
                new ObjectParameter("Nombre_Metodo_Pago", nombre_Metodo_Pago) :
                new ObjectParameter("Nombre_Metodo_Pago", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insertarMetodoPagos", nombre_Metodo_PagoParameter);
        }
    
        public virtual int SP_insertarOrdenCompras(Nullable<System.DateTime> fecha_Ultima_Orden_Compra, string ultimo_Numero_Factura, string codigo_Presupuestario_2016, string monto_Previo, string direccion_Archivo)
        {
            var fecha_Ultima_Orden_CompraParameter = fecha_Ultima_Orden_Compra.HasValue ?
                new ObjectParameter("Fecha_Ultima_Orden_Compra", fecha_Ultima_Orden_Compra) :
                new ObjectParameter("Fecha_Ultima_Orden_Compra", typeof(System.DateTime));
    
            var ultimo_Numero_FacturaParameter = ultimo_Numero_Factura != null ?
                new ObjectParameter("Ultimo_Numero_Factura", ultimo_Numero_Factura) :
                new ObjectParameter("Ultimo_Numero_Factura", typeof(string));
    
            var codigo_Presupuestario_2016Parameter = codigo_Presupuestario_2016 != null ?
                new ObjectParameter("Codigo_Presupuestario_2016", codigo_Presupuestario_2016) :
                new ObjectParameter("Codigo_Presupuestario_2016", typeof(string));
    
            var monto_PrevioParameter = monto_Previo != null ?
                new ObjectParameter("Monto_Previo", monto_Previo) :
                new ObjectParameter("Monto_Previo", typeof(string));
    
            var direccion_ArchivoParameter = direccion_Archivo != null ?
                new ObjectParameter("Direccion_Archivo", direccion_Archivo) :
                new ObjectParameter("Direccion_Archivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insertarOrdenCompras", fecha_Ultima_Orden_CompraParameter, ultimo_Numero_FacturaParameter, codigo_Presupuestario_2016Parameter, monto_PrevioParameter, direccion_ArchivoParameter);
        }
    
        public virtual int SP_insertarPerfiles(string nombre_Perfil, string descripcion)
        {
            var nombre_PerfilParameter = nombre_Perfil != null ?
                new ObjectParameter("Nombre_Perfil", nombre_Perfil) :
                new ObjectParameter("Nombre_Perfil", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insertarPerfiles", nombre_PerfilParameter, descripcionParameter);
        }
    
        public virtual int SP_insertarProductos(string nombre_Producto, Nullable<decimal> precio, string descripcion, string direccion_Fotografia, Nullable<int> proveedor_ManufactureroId, Nullable<int> proveedor_DistribuidorId)
        {
            var nombre_ProductoParameter = nombre_Producto != null ?
                new ObjectParameter("Nombre_Producto", nombre_Producto) :
                new ObjectParameter("Nombre_Producto", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var direccion_FotografiaParameter = direccion_Fotografia != null ?
                new ObjectParameter("Direccion_Fotografia", direccion_Fotografia) :
                new ObjectParameter("Direccion_Fotografia", typeof(string));
    
            var proveedor_ManufactureroIdParameter = proveedor_ManufactureroId.HasValue ?
                new ObjectParameter("Proveedor_ManufactureroId", proveedor_ManufactureroId) :
                new ObjectParameter("Proveedor_ManufactureroId", typeof(int));
    
            var proveedor_DistribuidorIdParameter = proveedor_DistribuidorId.HasValue ?
                new ObjectParameter("Proveedor_DistribuidorId", proveedor_DistribuidorId) :
                new ObjectParameter("Proveedor_DistribuidorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insertarProductos", nombre_ProductoParameter, precioParameter, descripcionParameter, direccion_FotografiaParameter, proveedor_ManufactureroIdParameter, proveedor_DistribuidorIdParameter);
        }
    
        public virtual int SP_insertarProveedores(string nombre_Proveedor, string correo_Proveedor, string nombre_Contacto, string telefono_Contacto, string ubicacion, string descripcion, Nullable<int> tipo_ProveedorId)
        {
            var nombre_ProveedorParameter = nombre_Proveedor != null ?
                new ObjectParameter("Nombre_Proveedor", nombre_Proveedor) :
                new ObjectParameter("Nombre_Proveedor", typeof(string));
    
            var correo_ProveedorParameter = correo_Proveedor != null ?
                new ObjectParameter("Correo_Proveedor", correo_Proveedor) :
                new ObjectParameter("Correo_Proveedor", typeof(string));
    
            var nombre_ContactoParameter = nombre_Contacto != null ?
                new ObjectParameter("Nombre_Contacto", nombre_Contacto) :
                new ObjectParameter("Nombre_Contacto", typeof(string));
    
            var telefono_ContactoParameter = telefono_Contacto != null ?
                new ObjectParameter("Telefono_Contacto", telefono_Contacto) :
                new ObjectParameter("Telefono_Contacto", typeof(string));
    
            var ubicacionParameter = ubicacion != null ?
                new ObjectParameter("Ubicacion", ubicacion) :
                new ObjectParameter("Ubicacion", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var tipo_ProveedorIdParameter = tipo_ProveedorId.HasValue ?
                new ObjectParameter("Tipo_ProveedorId", tipo_ProveedorId) :
                new ObjectParameter("Tipo_ProveedorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insertarProveedores", nombre_ProveedorParameter, correo_ProveedorParameter, nombre_ContactoParameter, telefono_ContactoParameter, ubicacionParameter, descripcionParameter, tipo_ProveedorIdParameter);
        }
    
        public virtual int SP_insertarTarjetas(string ultimos_Digitos_Tarjeta, Nullable<System.DateTime> fecha_Vencimiento_Tarjeta, string nombre_Persona_Asignada_A_Yarjeta, Nullable<int> tipo_TarjetaId)
        {
            var ultimos_Digitos_TarjetaParameter = ultimos_Digitos_Tarjeta != null ?
                new ObjectParameter("Ultimos_Digitos_Tarjeta", ultimos_Digitos_Tarjeta) :
                new ObjectParameter("Ultimos_Digitos_Tarjeta", typeof(string));
    
            var fecha_Vencimiento_TarjetaParameter = fecha_Vencimiento_Tarjeta.HasValue ?
                new ObjectParameter("Fecha_Vencimiento_Tarjeta", fecha_Vencimiento_Tarjeta) :
                new ObjectParameter("Fecha_Vencimiento_Tarjeta", typeof(System.DateTime));
    
            var nombre_Persona_Asignada_A_YarjetaParameter = nombre_Persona_Asignada_A_Yarjeta != null ?
                new ObjectParameter("Nombre_Persona_Asignada_A_Yarjeta", nombre_Persona_Asignada_A_Yarjeta) :
                new ObjectParameter("Nombre_Persona_Asignada_A_Yarjeta", typeof(string));
    
            var tipo_TarjetaIdParameter = tipo_TarjetaId.HasValue ?
                new ObjectParameter("Tipo_TarjetaId", tipo_TarjetaId) :
                new ObjectParameter("Tipo_TarjetaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insertarTarjetas", ultimos_Digitos_TarjetaParameter, fecha_Vencimiento_TarjetaParameter, nombre_Persona_Asignada_A_YarjetaParameter, tipo_TarjetaIdParameter);
        }
    
        public virtual int SP_insertarTipoContratos(string nombre_Tipo_Contrato, string descripcion)
        {
            var nombre_Tipo_ContratoParameter = nombre_Tipo_Contrato != null ?
                new ObjectParameter("Nombre_Tipo_Contrato", nombre_Tipo_Contrato) :
                new ObjectParameter("Nombre_Tipo_Contrato", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insertarTipoContratos", nombre_Tipo_ContratoParameter, descripcionParameter);
        }
    
        public virtual int SP_insertarTipoPagos(string nombre_Tipo_Pago)
        {
            var nombre_Tipo_PagoParameter = nombre_Tipo_Pago != null ?
                new ObjectParameter("Nombre_Tipo_Pago", nombre_Tipo_Pago) :
                new ObjectParameter("Nombre_Tipo_Pago", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insertarTipoPagos", nombre_Tipo_PagoParameter);
        }
    
        public virtual int SP_insertarUnidadNegocios(string numero_Unidad_Negocio, string nombre_Unidad_Negocio, string nombre_Previo_Unidad_Negocio)
        {
            var numero_Unidad_NegocioParameter = numero_Unidad_Negocio != null ?
                new ObjectParameter("Numero_Unidad_Negocio", numero_Unidad_Negocio) :
                new ObjectParameter("Numero_Unidad_Negocio", typeof(string));
    
            var nombre_Unidad_NegocioParameter = nombre_Unidad_Negocio != null ?
                new ObjectParameter("Nombre_Unidad_Negocio", nombre_Unidad_Negocio) :
                new ObjectParameter("Nombre_Unidad_Negocio", typeof(string));
    
            var nombre_Previo_Unidad_NegocioParameter = nombre_Previo_Unidad_Negocio != null ?
                new ObjectParameter("Nombre_Previo_Unidad_Negocio", nombre_Previo_Unidad_Negocio) :
                new ObjectParameter("Nombre_Previo_Unidad_Negocio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insertarUnidadNegocios", numero_Unidad_NegocioParameter, nombre_Unidad_NegocioParameter, nombre_Previo_Unidad_NegocioParameter);
        }
    
        public virtual int SP_insertarUsuarios(string nombre, string apellido, string email, string pass, string telefono, string codigo_Usuario, string username, Nullable<System.DateTime> fecha_Creacion, string direccion_Fotografia, Nullable<int> perfilId)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var codigo_UsuarioParameter = codigo_Usuario != null ?
                new ObjectParameter("Codigo_Usuario", codigo_Usuario) :
                new ObjectParameter("Codigo_Usuario", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var fecha_CreacionParameter = fecha_Creacion.HasValue ?
                new ObjectParameter("Fecha_Creacion", fecha_Creacion) :
                new ObjectParameter("Fecha_Creacion", typeof(System.DateTime));
    
            var direccion_FotografiaParameter = direccion_Fotografia != null ?
                new ObjectParameter("Direccion_Fotografia", direccion_Fotografia) :
                new ObjectParameter("Direccion_Fotografia", typeof(string));
    
            var perfilIdParameter = perfilId.HasValue ?
                new ObjectParameter("PerfilId", perfilId) :
                new ObjectParameter("PerfilId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insertarUsuarios", nombreParameter, apellidoParameter, emailParameter, passParameter, telefonoParameter, codigo_UsuarioParameter, usernameParameter, fecha_CreacionParameter, direccion_FotografiaParameter, perfilIdParameter);
        }
    
        public virtual ObjectResult<SP_selectAdministrator_Result> SP_selectAdministrator()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectAdministrator_Result>("SP_selectAdministrator");
        }
    
        public virtual ObjectResult<SP_selectAdminUserPermissions_Result> SP_selectAdminUserPermissions(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("usuarioId", usuarioId) :
                new ObjectParameter("usuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectAdminUserPermissions_Result>("SP_selectAdminUserPermissions", usuarioIdParameter);
        }
    
        public virtual ObjectResult<SP_selectAllBusinessunit_Result> SP_selectAllBusinessunit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectAllBusinessunit_Result>("SP_selectAllBusinessunit");
        }
    
        public virtual ObjectResult<SP_selectAllCards_Result> SP_selectAllCards()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectAllCards_Result>("SP_selectAllCards");
        }
    
        public virtual ObjectResult<SP_selectAllContractArea_Result> SP_selectAllContractArea()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectAllContractArea_Result>("SP_selectAllContractArea");
        }
    
        public virtual ObjectResult<SP_selectAllDetailsContract_Result> SP_selectAllDetailsContract(Nullable<int> contratoId)
        {
            var contratoIdParameter = contratoId.HasValue ?
                new ObjectParameter("contratoId", contratoId) :
                new ObjectParameter("contratoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectAllDetailsContract_Result>("SP_selectAllDetailsContract", contratoIdParameter);
        }
    
        public virtual ObjectResult<SP_selectAllMethodPayment_Result> SP_selectAllMethodPayment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectAllMethodPayment_Result>("SP_selectAllMethodPayment");
        }
    
        public virtual ObjectResult<SP_selectAllProducts_Result> SP_selectAllProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectAllProducts_Result>("SP_selectAllProducts");
        }
    
        public virtual ObjectResult<SP_selectAllProvider_Result> SP_selectAllProvider()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectAllProvider_Result>("SP_selectAllProvider");
        }
    
        public virtual ObjectResult<SP_selectAllPurchaseOrder_Result> SP_selectAllPurchaseOrder()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectAllPurchaseOrder_Result>("SP_selectAllPurchaseOrder");
        }
    
        public virtual ObjectResult<SP_selectAllTypeContract_Result> SP_selectAllTypeContract()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectAllTypeContract_Result>("SP_selectAllTypeContract");
        }
    
        public virtual ObjectResult<SP_selectAllTypeProvider_Result> SP_selectAllTypeProvider()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectAllTypeProvider_Result>("SP_selectAllTypeProvider");
        }
    
        public virtual ObjectResult<SP_selectAllUser_Result> SP_selectAllUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectAllUser_Result>("SP_selectAllUser");
        }
    
        public virtual ObjectResult<SP_selectApprover_Result> SP_selectApprover()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectApprover_Result>("SP_selectApprover");
        }
    
        public virtual ObjectResult<string> SP_selectBusinessUnit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_selectBusinessUnit");
        }
    
        public virtual ObjectResult<SP_selectCard_Result> SP_selectCard()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectCard_Result>("SP_selectCard");
        }
    
        public virtual ObjectResult<SP_selectContract_Result> SP_selectContract()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectContract_Result>("SP_selectContract");
        }
    
        public virtual ObjectResult<string> SP_selectContractArea()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_selectContractArea");
        }
    
        public virtual ObjectResult<SP_selectContractAreaById_Result> SP_selectContractAreaById(Nullable<int> area_ContratoId)
        {
            var area_ContratoIdParameter = area_ContratoId.HasValue ?
                new ObjectParameter("Area_ContratoId", area_ContratoId) :
                new ObjectParameter("Area_ContratoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectContractAreaById_Result>("SP_selectContractAreaById", area_ContratoIdParameter);
        }
    
        public virtual ObjectResult<SP_selectContractByArea_Result> SP_selectContractByArea(Nullable<int> codigoArea)
        {
            var codigoAreaParameter = codigoArea.HasValue ?
                new ObjectParameter("CodigoArea", codigoArea) :
                new ObjectParameter("CodigoArea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectContractByArea_Result>("SP_selectContractByArea", codigoAreaParameter);
        }
    
        public virtual ObjectResult<SP_SelectContractForEdit_Result> SP_SelectContractForEdit(Nullable<int> contratoId)
        {
            var contratoIdParameter = contratoId.HasValue ?
                new ObjectParameter("ContratoId", contratoId) :
                new ObjectParameter("ContratoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectContractForEdit_Result>("SP_SelectContractForEdit", contratoIdParameter);
        }
    
        public virtual ObjectResult<SP_selectDraftContract_Result> SP_selectDraftContract()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectDraftContract_Result>("SP_selectDraftContract");
        }
    
        public virtual ObjectResult<SP_selectDraftContractByArea_Result> SP_selectDraftContractByArea(Nullable<int> codigoArea)
        {
            var codigoAreaParameter = codigoArea.HasValue ?
                new ObjectParameter("CodigoArea", codigoArea) :
                new ObjectParameter("CodigoArea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectDraftContractByArea_Result>("SP_selectDraftContractByArea", codigoAreaParameter);
        }
    
        public virtual ObjectResult<SP_SelectDraftContractForEdit_Result> SP_SelectDraftContractForEdit(Nullable<int> contratoId)
        {
            var contratoIdParameter = contratoId.HasValue ?
                new ObjectParameter("ContratoId", contratoId) :
                new ObjectParameter("ContratoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectDraftContractForEdit_Result>("SP_SelectDraftContractForEdit", contratoIdParameter);
        }
    
        public virtual ObjectResult<string> SP_selectEmailByUSerId(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_selectEmailByUSerId", userIdParameter);
        }
    
        public virtual ObjectResult<SP_selectMethodPayment_Result> SP_selectMethodPayment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectMethodPayment_Result>("SP_selectMethodPayment");
        }
    
        public virtual ObjectResult<SP_selectMethodPaymentById_Result> SP_selectMethodPaymentById(Nullable<int> metodoPagoId)
        {
            var metodoPagoIdParameter = metodoPagoId.HasValue ?
                new ObjectParameter("MetodoPagoId", metodoPagoId) :
                new ObjectParameter("MetodoPagoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectMethodPaymentById_Result>("SP_selectMethodPaymentById", metodoPagoIdParameter);
        }
    
        public virtual ObjectResult<SP_SelectOrdenComprasById_Result> SP_SelectOrdenComprasById(Nullable<int> ordenCompraId)
        {
            var ordenCompraIdParameter = ordenCompraId.HasValue ?
                new ObjectParameter("OrdenCompraId", ordenCompraId) :
                new ObjectParameter("OrdenCompraId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectOrdenComprasById_Result>("SP_SelectOrdenComprasById", ordenCompraIdParameter);
        }
    
        public virtual ObjectResult<SP_selectPass_Result> SP_selectPass(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectPass_Result>("SP_selectPass", emailParameter);
        }
    
        public virtual ObjectResult<SP_selectProductById_Result> SP_selectProductById(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectProductById_Result>("SP_selectProductById", productIdParameter);
        }
    
        public virtual ObjectResult<SP_selectProductByName_Result> SP_selectProductByName(string productName)
        {
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectProductByName_Result>("SP_selectProductByName", productNameParameter);
        }
    
        public virtual ObjectResult<SP_selectProductByProviderId_Result> SP_selectProductByProviderId(Nullable<int> proveedorId)
        {
            var proveedorIdParameter = proveedorId.HasValue ?
                new ObjectParameter("ProveedorId", proveedorId) :
                new ObjectParameter("ProveedorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectProductByProviderId_Result>("SP_selectProductByProviderId", proveedorIdParameter);
        }
    
        public virtual ObjectResult<SP_selectProductsAccordingSuppliers_Result> SP_selectProductsAccordingSuppliers(Nullable<int> providerManufacturing, Nullable<int> providerVendor)
        {
            var providerManufacturingParameter = providerManufacturing.HasValue ?
                new ObjectParameter("ProviderManufacturing", providerManufacturing) :
                new ObjectParameter("ProviderManufacturing", typeof(int));
    
            var providerVendorParameter = providerVendor.HasValue ?
                new ObjectParameter("ProviderVendor", providerVendor) :
                new ObjectParameter("ProviderVendor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectProductsAccordingSuppliers_Result>("SP_selectProductsAccordingSuppliers", providerManufacturingParameter, providerVendorParameter);
        }
    
        public virtual ObjectResult<string> SP_selectProfiles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_selectProfiles");
        }
    
        public virtual ObjectResult<SP_selectProviderById_Result> SP_selectProviderById(Nullable<int> proveedorId)
        {
            var proveedorIdParameter = proveedorId.HasValue ?
                new ObjectParameter("ProveedorId", proveedorId) :
                new ObjectParameter("ProveedorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectProviderById_Result>("SP_selectProviderById", proveedorIdParameter);
        }
    
        public virtual ObjectResult<SP_selectProviderManufacturing_Result> SP_selectProviderManufacturing()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectProviderManufacturing_Result>("SP_selectProviderManufacturing");
        }
    
        public virtual ObjectResult<SP_selectProviderVender_Result> SP_selectProviderVender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectProviderVender_Result>("SP_selectProviderVender");
        }
    
        public virtual ObjectResult<SP_selectPurchaseOrder_Result> SP_selectPurchaseOrder()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectPurchaseOrder_Result>("SP_selectPurchaseOrder");
        }
    
        public virtual ObjectResult<SP_selectState_Result> SP_selectState()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectState_Result>("SP_selectState");
        }
    
        public virtual ObjectResult<SP_selectTarjetasById_Result> SP_selectTarjetasById(Nullable<int> tarjetaId)
        {
            var tarjetaIdParameter = tarjetaId.HasValue ?
                new ObjectParameter("TarjetaId", tarjetaId) :
                new ObjectParameter("TarjetaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectTarjetasById_Result>("SP_selectTarjetasById", tarjetaIdParameter);
        }
    
        public virtual ObjectResult<string> SP_selectTypeCard()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_selectTypeCard");
        }
    
        public virtual ObjectResult<SP_selectTypeContract_Result> SP_selectTypeContract()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectTypeContract_Result>("SP_selectTypeContract");
        }
    
        public virtual ObjectResult<SP_selectTypeContractById_Result> SP_selectTypeContractById(Nullable<int> tipoContratoId)
        {
            var tipoContratoIdParameter = tipoContratoId.HasValue ?
                new ObjectParameter("TipoContratoId", tipoContratoId) :
                new ObjectParameter("TipoContratoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectTypeContractById_Result>("SP_selectTypeContractById", tipoContratoIdParameter);
        }
    
        public virtual ObjectResult<SP_selectTypePayment_Result> SP_selectTypePayment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectTypePayment_Result>("SP_selectTypePayment");
        }
    
        public virtual ObjectResult<string> SP_selectTypeProvider()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_selectTypeProvider");
        }
    
        public virtual ObjectResult<SP_SelectUnidadNegociosById_Result> SP_SelectUnidadNegociosById(Nullable<int> unidadNegocioId)
        {
            var unidadNegocioIdParameter = unidadNegocioId.HasValue ?
                new ObjectParameter("UnidadNegocioId", unidadNegocioId) :
                new ObjectParameter("UnidadNegocioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectUnidadNegociosById_Result>("SP_SelectUnidadNegociosById", unidadNegocioIdParameter);
        }
    
        public virtual ObjectResult<SP_selectUserById_Result> SP_selectUserById(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_selectUserById_Result>("SP_selectUserById", usuarioIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_selectUserId(string username, string pass)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_selectUserId", usernameParameter, passParameter);
        }
    
        public virtual ObjectResult<string> SP_selectWeatherAlerts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_selectWeatherAlerts");
        }
    }
}
