//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema_alertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrato
    {
        public int ContratoId { get; set; }
        public string Nombre_Contrato { get; set; }
        public string Numero_Contrato { get; set; }
        public string Numero_Servicio_Contrato { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Finalizacion { get; set; }
        public decimal Costo_Total { get; set; }
        public decimal Costo_Por_Cada_Pago { get; set; }
        public System.DateTime Fecha_Renovacion_Pago { get; set; }
        public Nullable<int> Cantidad_Licencias { get; set; }
        public string Garantia { get; set; }
        public System.DateTime Fecha_Vencimiento_Garantia { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public string Descripcion { get; set; }
        public string Direccion_Archivo { get; set; }
        public int Proveedor_ManufactureroId { get; set; }
        public int Proveedor_DistribuidorId { get; set; }
        public int Usuario_AprobadorId { get; set; }
        public int Usuario_AdministradorId { get; set; }
        public int Tipo_ContratoId { get; set; }
        public int Metodo_PagoId { get; set; }
        public int Unidad_NegocioId { get; set; }
        public int Tipo_PagoId { get; set; }
        public int Orden_CompraId { get; set; }
        public int TarjetaId { get; set; }
        public int Area_ContratoId { get; set; }
        public int ProductoId { get; set; }
        public int RecordatorioId { get; set; }
        public int EstadoId { get; set; }
        public string Detalles_Producto { get; set; }
        public string Gastos { get; set; }
    
        public virtual area_contratos area_contratos { get; set; }
        public virtual estado estado { get; set; }
        public virtual metodo_pagos metodo_pagos { get; set; }
        public virtual orden_compras orden_compras { get; set; }
        public virtual producto producto { get; set; }
        public virtual proveedore proveedore { get; set; }
        public virtual proveedore proveedore1 { get; set; }
        public virtual recordatorio recordatorio { get; set; }
        public virtual tarjeta tarjeta { get; set; }
        public virtual tipo_contratos tipo_contratos { get; set; }
        public virtual tipo_pagos tipo_pagos { get; set; }
        public virtual unidad_negocios unidad_negocios { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
