//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema_alertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class metodo_pagos
    {
        public metodo_pagos()
        {
            this.Borradorcontratos = new HashSet<Borradorcontrato>();
            this.contratos = new HashSet<contrato>();
        }
    
        public int Metodo_PagoId { get; set; }
        public string Nombre_Metodo_Pago { get; set; }
    
        public virtual ICollection<Borradorcontrato> Borradorcontratos { get; set; }
        public virtual ICollection<contrato> contratos { get; set; }
    }
}
