//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema_alertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_compras
    {
        public orden_compras()
        {
            this.Borradorcontratos = new HashSet<Borradorcontrato>();
            this.contratos = new HashSet<contrato>();
        }
    
        public int Orden_CompraId { get; set; }
        public System.DateTime Fecha_Ultima_Orden_Compra { get; set; }
        public string Ultimo_Numero_Factura { get; set; }
        public string Codigo_Presupuestario2016 { get; set; }
        public string Monto_Previo { get; set; }
        public string Direccion_Archivo { get; set; }
    
        public virtual ICollection<Borradorcontrato> Borradorcontratos { get; set; }
        public virtual ICollection<contrato> contratos { get; set; }
    }
}
