//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema_alertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.Borradorcontratos = new HashSet<Borradorcontrato>();
            this.contratos = new HashSet<contrato>();
        }
    
        public int ProductoId { get; set; }
        public string Nombre_Producto { get; set; }
        public decimal Precio { get; set; }
        public string Descripcion { get; set; }
        public string Direccion_Fotografia { get; set; }
        public int Proveedor_ManufactureroId { get; set; }
        public int Proveedor_DistribuidorId { get; set; }
    
        public virtual ICollection<Borradorcontrato> Borradorcontratos { get; set; }
        public virtual ICollection<contrato> contratos { get; set; }
        public virtual proveedore proveedore { get; set; }
        public virtual proveedore proveedore1 { get; set; }
    }
}
