//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema_alertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedore
    {
        public proveedore()
        {
            this.Borradorcontratos = new HashSet<Borradorcontrato>();
            this.Borradorcontratos1 = new HashSet<Borradorcontrato>();
            this.contratos = new HashSet<contrato>();
            this.contratos1 = new HashSet<contrato>();
            this.productos = new HashSet<producto>();
            this.productos1 = new HashSet<producto>();
        }
    
        public int ProveedorId { get; set; }
        public string Nombre_Proveedor { get; set; }
        public string Correo_Proveedor { get; set; }
        public string Nombre_Contacto { get; set; }
        public string Telefono_Contacto { get; set; }
        public string Ubicacion { get; set; }
        public string Descripcion { get; set; }
        public int Tipo_ProveedorId { get; set; }
    
        public virtual ICollection<Borradorcontrato> Borradorcontratos { get; set; }
        public virtual ICollection<Borradorcontrato> Borradorcontratos1 { get; set; }
        public virtual ICollection<contrato> contratos { get; set; }
        public virtual ICollection<contrato> contratos1 { get; set; }
        public virtual ICollection<producto> productos { get; set; }
        public virtual ICollection<producto> productos1 { get; set; }
        public virtual tipo_proveedores tipo_proveedores { get; set; }
    }
}
