//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema_alertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recordatorio
    {
        public recordatorio()
        {
            this.Borradorcontratos = new HashSet<Borradorcontrato>();
            this.contratos = new HashSet<contrato>();
        }
    
        public int RecordatorioId { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Borradorcontrato> Borradorcontratos { get; set; }
        public virtual ICollection<contrato> contratos { get; set; }
    }
}
