//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema_alertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarjeta
    {
        public tarjeta()
        {
            this.Borradorcontratos = new HashSet<Borradorcontrato>();
            this.contratos = new HashSet<contrato>();
        }
    
        public int TarjetaId { get; set; }
        public string Ultimos_Digitos_Tarjeta { get; set; }
        public System.DateTime Fecha_Vencimiento_Tarjeta { get; set; }
        public string Nombre_Persona_Asignada_A_Tarjeta { get; set; }
        public int Tipo_TarjetaId { get; set; }
    
        public virtual ICollection<Borradorcontrato> Borradorcontratos { get; set; }
        public virtual ICollection<contrato> contratos { get; set; }
        public virtual tipo_tarjetas tipo_tarjetas { get; set; }
    }
}
