//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema_alertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_proveedores
    {
        public tipo_proveedores()
        {
            this.proveedores = new HashSet<proveedore>();
        }
    
        public int Tipo_ProveedorId { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<proveedore> proveedores { get; set; }
    }
}
