//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema_alertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios_perfiles_permisos
    {
        public int Usuario_Perfil_PermisoId { get; set; }
        public int UsuarioId { get; set; }
        public int PerfilId { get; set; }
        public int PermisoId { get; set; }
        public string Descripcion { get; set; }
    
        public virtual perfile perfile { get; set; }
        public virtual permiso permiso { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
