//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema_alertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.Borradorcontratos = new HashSet<Borradorcontrato>();
            this.Borradorcontratos1 = new HashSet<Borradorcontrato>();
            this.contratos = new HashSet<contrato>();
            this.contratos1 = new HashSet<contrato>();
            this.usuarios_perfiles_permisos = new HashSet<usuarios_perfiles_permisos>();
        }
    
        public int UsuarioId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string email { get; set; }
        public string pass { get; set; }
        public string Telefono { get; set; }
        public string Codigo_Usuario { get; set; }
        public string username { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public string Direccion_Fotografia { get; set; }
        public int PerfilId { get; set; }
        public byte[] pass2 { get; set; }
    
        public virtual ICollection<Borradorcontrato> Borradorcontratos { get; set; }
        public virtual ICollection<Borradorcontrato> Borradorcontratos1 { get; set; }
        public virtual ICollection<contrato> contratos { get; set; }
        public virtual ICollection<contrato> contratos1 { get; set; }
        public virtual perfile perfile { get; set; }
        public virtual ICollection<usuarios_perfiles_permisos> usuarios_perfiles_permisos { get; set; }
    }
}
